### ISSUE TITLE
Warning: Duplicate l10n entry 'EV_KS_warning5' ...

### ISSUE THREAD

**Issue by fdanapfel** [ZhooL/TSX_EnhancedVehicle#34] opened 2019-01-30 19:08 UTC
The mod produces the following warning in the log.txt every time it is being loaded:
...
Load mod: TSX_EnhancedVehicle (Version: 1.6.3.0) (Hash: 00b12b8dd93feb339ffa62f525982629)
Warning: Duplicate l10n entry 'EV_KS_warning5' in '/Users/user/Library/Application Support/FarmingSimulator2019/mods/TSX_EnhancedVehicle/modDesc_l10n_en.xml'. Ignoring this defintion.
...

Looking at the modDesc_l10n_en.xml there are indeed two lines with the same name:
...
`    <text name="EV_KS_warning5" text="* open the XML config(*) from EnhancedVehicle, set the variable 'ShuttleIsEnabled' to 'false' and reload config (default: KeyPad *)"/>`
...
`    <text name="EV_KS_warning5" text="* open the XML config(*) from EnhancedVehicle, set the variable 'ShuttleIsEnabled' to 'true' and reload config (default: KeyPad *)"/>`
...

Then name of the second line needs to be changed to 'EV_KS_warning8' to make this warning disappear.

**Comment by ZhooL** [comment] 2019-01-30 20:51
duplicate of #31

**Closed as completed by ZhooL** 2019-01-30 20:51 UTC
Labels: duplicate
