### ISSUE TITLE
XML resets on launch game

### ISSUE THREAD

**Issue by xCrazyDogx** [ZhooL/TSX_EnhancedVehicle#10] opened 2019-01-09 09:11 UTC
Hi ZhooL,

I am using version 1.5.0.0 so with added shuttle control.
Problem I have is my XML gets reset on launch.
So I can change /adjust in XML (under folder modssettings/TSX_EnhancedVehicle) but on launch it goes to default values.
Also trying to adjust file while ingame then presse keypad * but that didnt do anything either and closed game it still goes back to default, my settings wont stick.

I tried a lot of things but I can not figure out if it is my end or mod at this time, since i seem the only one with this problem?

**Comment by ZhooL** [comment] 2019-01-09 09:17
Which XML file did you edit ? There might be an old outdated file named TSX_EnhancedVehicle.xml and the new, current one named TSX_EnhancedVehicle_v1.xml. The first file can be deleted, changes to the second one should make it into the game. But I'll check again later today.

**Comment by xCrazyDogx** [comment] 2019-01-09 09:20
TSX_EnhancedVehicle_v1.xml 
I even deleted the file so game/mod creates it again reinstalled FS19, ok i keep it short, i only didnt do reinstall PC, everything else I tried.

Also offtopic showing in log iforgot to mention it dont think it is a big issue.
Warning (performance): Raw audio format D:/Steam Savegames/My Games/FarmingSimulator2019/mods/TSX_EnhancedVehicle/diff_lock.wav.

Anyways thx for the reply, i will keep trying to see if I can let it save properly and take your time, I understand people have lives and things to do and this is a hobby.

**Comment by ZhooL** [comment] 2019-01-09 09:29
Yeah I'm on work right now ;-) But I'll check today evening. The audio warning is already known and will be fixed soon.

**Comment by ZhooL** [comment] 2019-01-09 18:20
fixed in 1.5.0.2

**Closed as completed by ZhooL** 2019-01-09 18:20 UTC
Labels: bug

**Comment by xCrazyDogx** [comment] 2019-01-09 19:07
Thx working perfect on my end now when it comes to XML settings saving.

Except the keypad * doesnt seem to work, even if I bind it to other key it does not reload XML.

**Comment by ZhooL** [comment] 2019-01-09 20:31
Hmm can't reproduce your issue. I'm in game, change something in the XML from true to false, press "keypad *" back in game and the affected HUD element disappears.
